# Generated by Django 4.2.16 on 2025-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryadvancerequest',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='leave_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default=1234567890, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.CharField(default='Unknown Guardian', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_assigned',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='Unknown Guardian', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.TextField(default='unknown@example.com'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='SalaryAdvanceRequest',
        ),
    ]
